build:
  maxIssues: 1

complexity:
  ComplexMethod:
    threshold: 15
    ignoreSingleWhenExpression: true
    ignoreSimpleWhenEntries: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20

exceptions:
  TooGenericExceptionCaught:
    exceptionNames:
      - Error
      - Exception
      - RuntimeException
      - Throwable

comments:
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: false
  CommentOverPrivateFunction:
    active: false

potential-bugs:
  LateinitUsage:
    active: false
